apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opencost-admin-token
spec:
  encryptedData:
    admin-token: AgAFLBft8FbCpA/iFmef/5MfA/u9wsatPNgD0nhFWlh14hDpnnBpXnXRBULjKLGmFDaffCMe1ZPvxDKhJKNE2BHYhumWIUIs2UsH07lZiY654cWNWiBri3xH/UcLs4QSUzKiufuY7QsAeP6y5c3w8awxg6A0q/qD3FAlzv/Ib5KBln28zXtOFRsigV5abCCWVDykOOXsM5TbSzU/XdspmA37DNY2k+Lo3xIKV/8xw2rFoXpfv6jahTjAv2QIf9e+HJ+ydFK+UL6n0FEka3CB+jXA3ZJqCREHWBMmCw0tfPt+R1q5QjEogYhvg3CrdqMAPr3SQtg+mO3sejpzKGkUwF/cqj2JGGMfd0pK0RjK3id1REKDKMdqoDp7AJysq/o7xdVSxTRwlpat1TVq/vSoVvg0wZxXLfBwt83TLXTbC/kYO+HsfaoiUgJ4aSijaICQWQZUy1YzxMJaspK3/aOoUGyhBNPXT7EpVEHuOjJbJiqr83Wkrqrp/ElxUH45ZPQaeOX+wS0spYIjnSopylIxjTqCbvGgR0RHk+08qvCfvdaPGwX/8+sY6tZtgYFbrrJmLTOUoP6PzbdmUp5NYMLc3rbqqcMpo55UIKJWbuiWQvPug1ktl7OuvFETN3oayx6JJ5V0IizecUUNRFKy5BcufOh3SLXWqmebl3eA9DAJb3s5BigVVd51Wg8cj/mJ/Pa1SN6ga+N3LzoTI8AF6iw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opencost-admin-token
