---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opencost-admin-token
spec:
  encryptedData:
    admin-token: AgAqEJZcA5NnLP281ZcSkXaJwVsaISt+M4HCfmEIKEjaECD5Vvo1Mr7SCMGOcyqrZ/MxjR8H5YXTv+U4fGJSzgY1uPabujjHm8Xsgdmz0S99GoTyT28mEa87MOc3GkOjtNt6Q6q5u0iCwj6iFi/Lm5bl4Y2cgsUBPt0dcO9uHhiiygjJf4/Dxfq/J6ie3Bc0QY/MyJddkOEbXiPWtOUgVwQVSlVncslY4gnNeHeaALgZjJ5jbEhovif19BtGwYSwyrTXLuZwN8KqsTFWWhMEkNq148bYhoXpTOxZ12Dm30nkzlxySZ9u9Lk2azE/knd9qrkWoBOAnDMc9CglL1cDWC8AAwM13QVb5vwH9dFYm3bb5RY5QJCXEwUaGN0vlfYPWcg44pFan5CNg2BMbPOCmK+vYsLPupUNhTW3Pd3CnLFr2DSC9aQa8Y9Oi3gPA14pf0eAXEb+bLd/wDPlpY2X5HZJUmZR8tWVxMiKr5jJ792vCCd7K2y0/6j16pmCfvrtBpY9hf2Nr8fhIFVynXhZm83CDxpU5TdTm5MvNBNDPJwfz0981Cl819sqRtGQBU1fyTiUukAmFL+QtEp4iJnMCxKVAE8oX7SKu80BJB3P5icwGQ1RDmKXFjoqZpnY12roKCEs2tV6In9JaXsWk/SKXlsvzxXg+X6/Kgcc1HtsPyKzO8AjSaTMBgGHYyGitNE2wWhCYjfsdi3eLHIvAI1n4/MHF1OvKawiVK75kWj9kMY+h0rJWlM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opencost-admin-token
    type: Opaque

