apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: atm/argo-setup
      files:
      - path: "argocd/apps/*/cert-manager/values.yaml"
  template:
    metadata:
      name: 'cert-manager-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://charts.jetstack.io
          targetRevision: v1.17.0
          chart: cert-manager
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/cert-manager/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: atm/argo-setup
          ref: values
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: atm/argo-setup
          path: "argocd/apps/demo/cert-manager/clusterissuer.yaml" # Hard coded to demo env. Wildcard isn't working in this context. 
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true