apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-issuer
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: atm/argo-setup
      files:
      - path: "argocd/apps/*/cluster-issuer/values.yaml"
  template:
    metadata:
      name: 'cluster-issuer-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://charts.adfinis.com
          targetRevision: 0.3.0
          chart: cert-manager-issuers
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/cluster-issuer/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: atm/argo-setup
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true