apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: main
      files:
      - path: "argocd/apps/*/envoy-gateway/values.yaml"
  template:
    metadata:
      name: 'envoy-gateway-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      sources:
        - repoURL: docker.io/envoyproxy
          targetRevision: v1.7.0
          chart: gateway-helm
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/envoy-gateway/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
