apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: folding-at-home
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: fah-alt-chart
      files:
      - path: "argocd/apps/*/folding-at-home/values.yaml"
  template:
    metadata:
      name: 'folding-at-home-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/daveneeley/helm-foldingathome.git
          targetRevision: master
          path: .
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/folding-at-home/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: fah-alt-chart
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: folding-at-home
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true