apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: folding-at-home
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: cdp/kcm-3646
      files:
      - path: "argocd/apps/*/folding-at-home/values.yaml"
  template:
    metadata:
      name: 'folding-at-home-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://pcktdmp.github.io/charts
          chart: fahclient
          targetRevision: 2.6.0
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/folding-at-home/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: cdp/kcm-3646
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: folding-at-home
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true