apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-resources
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: main
      directories:
      - path: "argocd/apps/*/gateway-resources"
  template:
    metadata:
      name: 'gateway-resources-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      source:
        repoURL: https://github.com/opencost/opencost-infra.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true