apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: atm/argo-setup
      files:
      - path: "argocd/apps/demo/ingress-nginx/values.yaml"
  template:
    metadata:
      name: 'ingress-nginx-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.8.3
          chart: ingress-nginx
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/ingress-nginx/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: atm/argo-setup
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
