apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: load-generator
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: cdp/kcm-3645-ubuntu
      files:
      - path: "argocd/apps/*/load-generator/values.yaml"
  template:
    metadata:
      name: 'load-generator-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://charts.fairwinds.com/incubator
          chart: load-generator
          targetRevision: 0.1.2
          helm:
            valueFiles:
            - '$values/argocd/apps/{{ index .path.segments 2 }}/load-generator/values.yaml'
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: cdp/kcm-3645-ubuntu
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: load-generator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
