apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opencost-secrets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: main
      files:
      - path: "argocd/apps/*/opencost-secrets/secrets.yaml"
  template:
    metadata:
      name: 'opencost-secrets-{{ index .path.segments 2 }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/opencost/opencost-infra.git
          targetRevision: main
          path: "argocd/apps/{{ index .path.segments 2 }}/opencost-secrets"
      destination:
        server: https://kubernetes.default.svc
        namespace: opencost
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
