apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
spec:
  generators:
  - git:
      repoURL: https://github.com/kubecost/opencost-infra.git
      revision: HEAD
      files:
      - path: "apps/*/prometheus/values.yaml"
  template:
    metadata:
      name: 'prometheus-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 27.5.1
        chart: prometheus
        helm:
          valueFiles:
          - '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: prometheus
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
