apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reference-grant
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/opencost/opencost-infra.git
      revision: main
      directories:
      - path: "argocd/apps/*/reference-grant-*"
  template:
    metadata:
      name: 'reference-grant-{{ index .path.segments 2 }}-{{ .path.basename | trimPrefix "reference-grant-" }}'
      labels:
        debug.argocd.argoproj.io/stage: '{{ index .path.segments 2 }}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: https://github.com/opencost/opencost-infra.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename | trimPrefix "reference-grant-" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
