autoDiscovery:
  clusterName: opencost

cloudProvider: oci

oci:
  region: us-ashburn-1
  useInstancePrincipal: false
  configFile: /etc/oci/config

extraVolumes:
  - name: oci-credentials
    secret:
      secretName: cluster-autoscaler-oci-credentials
      items:
        - key: TENANCY_ID
          path: tenancy
        - key: USER_ID
          path: user
        - key: FINGERPRINT
          path: fingerprint
        - key: PRIVATE_KEY
          path: key.pem
        - key: COMPARTMENT_ID
          path: compartment

extraVolumeMounts:
  - name: oci-credentials
    mountPath: /etc/oci
    readOnly: true

initContainers:
  - name: create-oci-config
    image: busybox
    command:
      - sh
      - -c
      - |
        cat <<EOF > /etc/oci/config
        [DEFAULT]
        user=$(cat /etc/oci/user)
        fingerprint=$(cat /etc/oci/fingerprint)
        key_file=/etc/oci/key.pem
        tenancy=$(cat /etc/oci/tenancy)
        region=us-ashburn-1
        compartment=$(cat /etc/oci/compartment)
        EOF
    volumeMounts:
      - name: oci-credentials
        mountPath: /etc/oci
        readOnly: true

extraArgs:
  cloud-config: /etc/oci/config