autoDiscovery:
  clusterName: opencost

cloudProvider: oci

oci:
  region: us-ashburn-1

extraVolumes:
  - name: oci-credentials
    secret:
      secretName: cluster-autoscaler-oci-credentials

extraVolumeMounts:
  - name: oci-credentials
    mountPath: /etc/oci
    readOnly: true

env:
  - name: OCI_CONFIG_FILE
    value: /etc/oci/config