autoDiscovery:
  clusterName: opencost

cloudProvider: oci

oci:
  region: us-ashburn-1

extraEnv:
  - name: OCI_USE_INSTANCE_PRINCIPAL
    value: "true"
  - name: OCI_REGION
    value: "us-ashburn-1"