_1: &email Christian.Petersen2@ibm.com
_2: &solvers
- http01:
    gatewayHTTPRoute:
      parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-gateway
        namespace: envoy-gateway-system
        sectionName: http
        port: 80

clusterIssuers:
- name: letsencrypt-demo
  spec:
    acme:
      email: *email
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-demo-account-key
      solvers: *solvers