opencost:
  metrics:
    kubeStateMetrics:
      emitNamespaceAnnotations: true
      emitPodAnnotations: true
  ui:
    ingress:
      enabled: false
    image:
      fullImageName: ghcr.io/opencost/opencost-ui:develop-71c0b43
  mcp:
    ingress:
      enabled: false
  prometheus:
    internal:
      serviceName: prometheus-kube-prometheus-prometheus
      port: 9090
  exporter:
    prometheusDataSource:
      queryResolutionSeconds: "60"
    image:
      fullImageName: ghcr.io/opencost/opencost:develop-bdb45bc
